### ISSUE TITLE
gcloud DNS: nameserver did not return the expected TXT record

### ISSUE THREAD

**Issue by cevich** [terraform-providers/terraform-provider-acme#65]
Hi, I'm having problems with a multi-zone SAN setup in 1.3 where the challenge TXT records are being created incorrectly in the top-level zone, and therefore are not resolvable.  I can reproduce this in my test environment, though in production I eventually managed to get the cert. after a great number of retries applying my terraform config.  All zones (including in test) are accessible by public DNS, only the subdomains change for the test environment and I use the staging server `https://acme-staging-v02.api.letsencrypt.org/directory`

The relevant part of my terraform configuration for looks similar to this:

```hcl
data "template_file" "domain_ns" {
    count = "4"
    // Must subtract trailing period
    template = "${substr(data.google_dns_managed_zone.domain.name_servers[count.index],
                         0,
                         length(data.google_dns_managed_zone.domain.name_servers[count.index]) - 1)}"
}

resource "acme_certificate" "domain" {
    account_key_pem = "${acme_registration.reg.account_key_pem}"
    // Must subtract trailing period
    common_name = "${substr(data.google_dns_managed_zone.domain.dns_name,
                            0,
                            length(data.google_dns_managed_zone.domain.dns_name) - 1)}"
    subject_alternative_names = ["${local.sans}"]
    key_type = "${tls_private_key.cert_private_key.rsa_bits}"
    min_days_remaining = "15"
    certificate_p12_password = "${var.certpassword}"
    // decouple from default nameservers on runtime host
    recursive_nameservers = ["${data.template_file.domain_ns.*.rendered}"]

    dns_challenge {
        provider = "gcloud"
        config {
            GCE_POLLING_INTERVAL = "30"
            GCE_PROPAGATION_TIMEOUT = "120"
            GCE_TTL = "60"
            GCE_PROJECT = "${var.project}"
            GCE_SERVICE_ACCOUNT_FILE = "${var.gcejson}"
        }
    }
}
```

Using `example.com` as the **dns_name** and with `local.sans` containing:

* `*.example.com`
* `*.test.example.com`
* `*.stage.example.com`
* `*.prod.example.com`

I see this (and two other similar) records show up in the top-level `example-com` zone:

```
_acme-challenge.test.example.com. | TXT | 60 | "blah1234blah"
```

Which definitely won't resolve, that record needs to be added to the subdomain zone`test-example-com` zone.  Any client trying to resolve `_acme-challenge.test.example.com.` will look in the `test-example-com` subdomain zone based on the glue record defined in `example-com`:

```
test.example.com. | NS | 86400 | ns-cloud-a1.googledomains.com.
ns-cloud-a2.googledomains.com.
ns-cloud-a3.googledomains.com.
ns-cloud-a4.googledomains.com.
```

I do have my setup working in production, so at some point this wasn't a problem.  I'm not sure if that was possibly due to something I changed on my end or if the acme provider has a bug.

**Comment by Temikus** [comment]
I'm experiencing the same with `digitalocean` DNS. Rolling the acme provider back to `1.3.3` resolved it.

**Comment by cevich** [comment]
Interesting, I'm glad to know I'm not the only one hitting this, thanks for the workaround hint, I'll give that a shot.

**Comment by vancluever** [comment]
@cevich I can't comment on the DO provider but the Google Cloud provider has been causing issues for a few people - this will be resolved when we move to the latest version of lego in the next release.

**Comment by vancluever** [comment]
Should be fixed with the v1.4.0 release (specifically Google Cloud related).

**Comment by cevich** [comment]
Thanks!

**Comment by Temikus** [comment]
I'm still having issues with 1.4.0 release. Should I file a new issue?

**Comment by vancluever** [comment]
@Temikus please do!

**Comment by rbrockz** [comment]
@Temikus, did you happen to open a new issue for this? I'm seeing this on v1.3.3 and v1.5.0. Did you happen to find a work around for this?

**Comment by Temikus** [comment]
@rbrockz I did, but it will not get you far I’m afraid: https://github.com/terraform-providers/terraform-provider-acme/issues/87 workaround is inelegant - just retry a bunch of times :/ I’m suspecting there may be some issues on my end due to DNS interception, but didn’t have time yet to verify that theory.
